### ISSUE TITLE
js-controller error on start of adapter

### ISSUE THREAD

**Issue by ichtyp** [iobroker-community-adapters/ioBroker.vofo-speedtest#141]
Hi Peter,

my adapter won't even start up and ends with the following log entry:

<html>
<body>

host.iobroker | 2022-11-09 06:12:00.663 | error | instance system.adapter.vofo-speedtest.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --

</body>
</html>

I just installed it, here are my versions used:

CPU: 480 %
RAM: 5,6 %
Uptime: 4d23h
JS-Controller: Available: 4.0.23
Installed: 4.0.23
Events: ⇥19 / ↦14
Platform: freebsd
operating system: freebsd
Architecture: x64
CPUs: 8
Speed: 2200 MHz
Model: Intel(R) Atom(TM) CPU C3758 @ 2.20GHz
RAM: 31.9 GB
System uptime: 68 d. 19:14:17
Node.js: v18.7.0
time: 1667970966727
timeOffset: -60
adapters count: 531
NPM: 8.5.2
Disk size: 26112.0 GB
Disk free: 26094.4 GB
Uptime: 4 d. 23:15:14
Active instances: 17
Path: /opt/iobroker/

If I can provide you with more info or logoutput, please just let me know. I used v0.0.13

Best regards

**Comment by nicomania** [comment]
Same here, won't even start.

**Comment by ManitheHobbit** [comment]
I have the same problem.

**Comment by rof999** [comment]
Are there any plans to solve this issue?
I´m facing the same problem...

**Comment by peterbaumert** [comment]
could you try https://github.com/peterbaumert/ioBroker.vofo-speedtest/issues/8#issuecomment-762891818

**Comment by peterbaumert** [comment]
so in the iobroker directory do a
```
npm install node-libcurl
```
and it works for me. seems like on node update this breaks

**Comment by ichtyp** [comment]
I tried both:

npm install node-libcurl 

and 

npm rebuild
npm install

but it did not work. 

This occurs when trying to let it run directly:

```
root@iobroker:/opt/iobroker # node node_modules/iobroker.vofo-speedtest/main.js --force --logs
ld-elf.so.1: /opt/iobroker/node_modules/iobroker.vofo-speedtest/node_modules/node-libcurl/lib/binding/node_libcurl.node: Undefined symbol "curl_version_info"
```

**Comment by mcm1957** [comment]
If this problem still exists with current release (2.0.0) , please open a new issue.
