### ISSUE TITLE
Adapter v1.0.1

### ISSUE THREAD

**Issue by Klaus-Lucas** [iobroker-community-adapters/ioBroker.vofo-speedtest#193]
Ich installiere zu erstem Mal den Adapter und er wird in der Version 1.0.1 angeboten:
![klu_008](https://github.com/peterbaumert/ioBroker.vofo-speedtest/assets/36620907/241650c9-cd6f-474d-b44e-9363893b6562)

Im Log findet man:
2024-01-05 12:06:01.004 - info: host.iobroker instance system.adapter.luftdaten.0 terminated with code 0 (NO_ERROR)
2024-01-05 12:07:09.262 - error: host.iobroker Invalid request getRepository. "callback"(false) or "from"(true) is null
2024-01-05 12:07:22.435 - info: host.iobroker iobroker add vofo-speedtest auto --host iobroker --debug
2024-01-05 12:07:23.053 - info: host.iobroker iobroker NPM version: 10.2.3
2024-01-05 12:07:23.053 - info: host.iobroker iobroker Installing iobroker.vofo-speedtest@1.0.1... (System call)

Zudem kommt bei der Installation eine Warnung:
![klu_009](https://github.com/peterbaumert/ioBroker.vofo-speedtest/assets/36620907/e2b31aee-7a7e-48f7-80c5-1ac039e2b241)
Installiert wird aber die Version 0.0.13:
![klu_010](https://github.com/peterbaumert/ioBroker.vofo-speedtest/assets/36620907/8f667125-846e-4746-a32b-224da7d8113f)
Warum dann auch die Version 1.0.1 erneut als herunterladbar angeboten wird:
![klu_014](https://github.com/peterbaumert/ioBroker.vofo-speedtest/assets/36620907/d8d443de-77be-4698-99a3-773bd7fdeece)
![klu_013](https://github.com/peterbaumert/ioBroker.vofo-speedtest/assets/36620907/a42c6bbf-386a-4af8-a816-38397c38dc7b)

![klu_015](https://github.com/peterbaumert/ioBroker.vofo-speedtest/assets/36620907/872204c1-d183-4e55-8df0-0d7d5c8a6091)
Es bleibt aber bei der Version 0.0.13.

**Versions:**  
 - Adapter version: soll 1.01 ist 0.0.13
 - Admin version: 6.13.15
 - JS-Controller version: 5.0.17
 - Node version: 18.19.0
 - Operating system: Ubuntu 22.04.3 LTS

**Comment by rof999** [comment]
Same here.

**Comment by krafel** [comment]
I have the very same effects here

**Comment by mcm1957** [comment]
release 1.x.x was misconfigure.
Please install / test / use 2.0.0
