### ISSUE TITLE
Adapterinstallation schlägt fehl

### ISSUE THREAD

**Issue by skvarel** [iobroker-community-adapters/ioBroker.vofo-speedtest#56]
Ich bekomme den Adapter nicht installiert.

![grafik](https://user-images.githubusercontent.com/1114419/129036167-542b50f4-f0e6-405b-8ec3-2a5be734428a.png)

![grafik](https://user-images.githubusercontent.com/1114419/129036568-642ec183-5cb8-4c48-b2f5-3edceb2e0b1a.png)

System:
![grafik](https://user-images.githubusercontent.com/1114419/129036435-0009ffb3-e7ec-4f8b-9cb8-47ddf0bd1d54.png)

Admin: v5.1.23
js-controller: 3.3.15

**Comment by peterbaumert** [comment]
Curl bitte installieren und nochmal testen

**Comment by skvarel** [comment]
curl v 7.64.0 ist instaliiert.

Sonst hätte ich den ioBroker doch gar nihct installieruen können, oder?
![grafik](https://user-images.githubusercontent.com/1114419/129084383-e4c7ee9b-f4ed-4850-8f5a-7877dc6e670d.png)

**Comment by peterbaumert** [comment]
Dann kommt wohl bei manchen distros das libcurl dev net mit. Kannste danach mal suchen mit apt und es installieren?
